apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi-deployment
  labels:
    app: ombi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ombi
  template:
    metadata:
      labels:
        app: ombi

    spec:
    containers:
        - name: ombi
          image: ghcr.io/linuxserver/ombi
          resources:
            requests:
              memory: "512Mi"
              cpu: "1000m"
          env:
            - name: PUID
              value: "999"
            - name: PGID
              value: "999"
          ports:
            - containerPort: 3579
          volumeMounts:
            - mountPath: /config
              name: ombi-config
    volumes:
      - name: ombi-config
        hostPath: 
          path: /opt/plexstack/ombi
---
kind: Service
apiVersion: v1
metadata:
  name: ombi-service
spec:
  selector:
    app: ombi
  ports:
  - protocol: TCP
    port: 3579
    targetPort: 3579
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-ombi
  namespace: plexstack
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - ombi.ccrow.org
      secretName: ombi-tls
  rules:
    - host: ombi.ccrow.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ombi-service
                port:
                  number: 3579
